steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/heart-rate-app10', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/heart-rate-app10']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy heart-rate-app10 \
      --image gcr.io/$PROJECT_ID/heart-rate-app10 \
      --platform managed \
      --region us-central1 \
      --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/heart-rate-app10'

logsBucket: 'gs://prophet-428401_cloudbuild'