steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/pnuh/heart-rate-app11', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/pnuh/heart-rate-app11']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy heart-rate-app11 \
      --image asia-northeast3-docker.pkg.dev/$PROJECT_ID/pnuh/heart-rate-app11 \
      --platform managed \
      --region asia-northeast3 \
      --allow-unauthenticated

images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/pnuh/heart-rate-app11'

options:
  logging: CLOUD_LOGGING_ONLY